blank_issues_enabled: true
contact_links:
  - name: User support issue
    url: https://confluence.ecmwf.int/site/support
    about: Need help installing or running ECMWF software? Reach out to user support.
