name: Maintenance request
description: Request a dependency upgrade or a documentation improvement.
labels: []
body:
  - type: textarea
    id: request
    attributes:
      label: What maintenance does this project need?
      description: e.g. Request a dependency upgrade or a documentation improvement.
